FROM node AS builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --legacy-peer-deps

COPY . .

ARG NEXT_PUBLIC_BackEnd_API
ARG NEXT_PUBLIC_BackEnd_API_SSR
ENV NEXT_PUBLIC_BackEnd_API=${NEXT_PUBLIC_BackEnd_API}
ENV NEXT_PUBLIC_BackEnd_API_SSR=${NEXT_PUBLIC_BackEnd_API_SSR}

RUN npm run build

FROM node AS production

WORKDIR /app

COPY --from=builder /app ./

EXPOSE 3000

CMD ["npm", "start"]
